### ISSUE TITLE
watch task fails with "Unexpected packet from actor server1..." error

### ISSUE THREAD

**Issue by louisremi** [mozilla/node-firefox-examples-gulp#3]
I successfully installed the demo and launched it  inside FirefoxOS 3.0 simulator from the command line, but as soon as I edit the css and save the file, the npm task crashes with the following error:

```
/home/louisremi/Workspace/node-firefox-examples-gulp-master/node_modules/node-firefox-start-simulator/index.js:181
            throw error;
                  ^
Error: Unexpected packet from actor server1.conn1.child8/24{"from":"server1.conn1.child8/24"}
    at EventEmitter.extend.handleMessage (/home/louisremi/Workspace/node-firefox-examples-gulp-master/node_modules/node-firefox-connect/node_modules/firefox-client/lib/client.js:173:13)
    at EventEmitter.extend.readMessage (/home/louisremi/Workspace/node-firefox-examples-gulp-master/node_modules/node-firefox-connect/node_modules/firefox-client/lib/client.js:220:10)
    at EventEmitter.extend.onData (/home/louisremi/Workspace/node-firefox-examples-gulp-master/node_modules/node-firefox-connect/node_modules/firefox-client/lib/client.js:186:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at TCP.onread (net.js:517:20)
```

Could it help to try a different simulator? I'll try this later today.

**Comment by louisremi** [comment]
It works using Firefox OS Simulator 2.0, indeed : )
